# Change these first
owner: querkmachine # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository
delay: 2000 # Wait 2 seconds between tests

sites:
  # Main things
  - name: beeps.website
    url: https://beeps.website
  - name: beeps.gay
    url: https://beeps.gay
  - name: social.beeps.gay
    url: https://social.beeps.gay
  # Side projects
  - name: bird.horse
    url: https://bird.horse
  - name: BW
    url: $BW_URL
  - name: BW Gallery
    url: $BW_URL_GALLERY
  - name: BW Stories 
    url: $BW_URL_STORIES
  - name: bronies.wiki
    url: https://bronies.wiki
  - name: Darn Blimps
    url: https://darnblimps.com
  - name: Encyclopedia Robotica
    url: https://encyclopediarobotica.org
  - name: Kimgur
    url: https://kimgur.com
  - name: placeholder.rocks
    url: https://placeholder.rocks
  - name: placeponi.es
    url: https://placeponi.es
  - name: Projects archive
    url: https://projects.berly.kim
  - name: The Software Bundle
    url: https://bundle.software
  - name: Twitter archive
    url: https://tweets.beeps.website
  # Redirects
  - name: "[REDIR] berly.kim"
    url: https://berly.kim
  - name: "[REDIR] furrified.com"
    url: https://furrified.com
  - name: "[REDIR] greysadventures.com"
    url: https://greysadventures.com
  - name: "[REDIR] robat.space"
    url: https://robat.space

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: beeps' stuff status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
