# Change these first
owner: querkmachine # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository
delay: 2000 # Wait 2 seconds between tests

sites:
  # Main things
  - name: "[MAIN] beeps.website"
    url: https://beeps.website
  - name: "[MAIN] beeps.gay"
    url: https://beeps.gay
  - name: "[MAIN] social.beeps.gay"
    url: https://social.beeps.gay
    
  # Side projects
  - name: "[PROJECT] BW"
    url: $BW_URL
  - name: "[PROJECT] BW Stories "
    url: $BW_URL_STORIES
  - name: "[PROJECT] Encyclopedia Robotica"
    url: https://encyclopediarobotica.org
  - name: "[PROJECT] placeholder.rocks"
    url: https://placeholder.rocks
  - name: "[PROJECT] placeponi.es"
    url: https://placeponi.es
  - name: "[PROJECT] The Software Bundle"
    url: https://bundle.software

  # Placeholder pages and domains
  - name: "[PLACEHOLDER] bird.horse"
    url: https://bird.horse
  - name: "[PLACEHOLDER] bronies.wiki"
    url: http://bronies.wiki

  # Archives
  - name: "[ARCHIVE] Darn Blimps"
    url: https://darnblimps.com
  - name: "[ARCHIVE] Emby"
    url: $EMBY_URL
  - name: "[ARCHIVE] Public file store"
    url: https://files.beeps.gay/
  - name: "[ARCHIVE] Kimgur"
    url: https://kimgur.com
  - name: "[ARCHIVE] Projects archive"
    url: https://projects.berly.kim
  - name: "[ARCHIVE] Twitter archive"
    url: https://tweets.beeps.website
    
  # Redirects
  - name: "[REDIRECT] berly.kim"
    url: https://berly.kim
  - name: "[REDIRECT] furrified.com"
    url: https://furrified.com
  - name: "[REDIRECT] greysadventures.com"
    url: https://greysadventures.com
  - name: "[REDIRECT] robat.space"
    url: https://robat.space

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: beeps' stuff status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
